server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UndefinedException/springcloud-config.git #GitHub上面的git仓库名字
          username: UndefinedException
          password: ljd19991209
          ####搜索目录
          search-paths:
            - springcloud-config
          force-pull: true
      ####读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
